variables:
  iOSRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_iOS_v3_0_0_FULL.zip?_ga=2.79185814.368877217.1583320605-5559409.1503304822'
  MacRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Mac_v3_0_0_FULL.zip?_ga=2.78400662.368877217.1583320605-5559409.1503304822'
  #WindowsRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(x86)_v2_9_3_FULL.zip'
  WindowsRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(x86)_v3_0_0_FULL.zip?_ga=2.264657869.391401122.1584692818-113887004.1555555580'

jobs:

#Windows demo

  - template: cicd/templates/build-Windows-QT.yml
    parameters:
      displayName: 'WindowsOpenVideoCall'
      workingDirectory: 'Group-Video/OpenVideoCall-Windows'
      scheme: 'OpenVideoCall'
      sdkurl: $(WindowsRTCSDK)
      solutionName: ''
