# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

parameters:
  displayName: ''
  workingDirectory: ''
  scheme: ''
  sdkurl: ''
  solutionName: ''
jobs:
  - job: ${{ parameters.displayName }}Build
    displayName: ${{ parameters.displayName }}

    pool:
      name: 'Default'

    variables:
      solution: '${{ parameters.workingDirectory }}/${{ parameters.solutionName }}'
      buildPlatform: 'win32'
      buildConfiguration: 'Release'
   
    steps:
      - script: echo "${{ parameters.sdkurl }}"
      - powershell: Windows/cicd/scripts/downloadsdk.ps1 "${{ parameters.sdkurl }}"
   
      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: 'AgoraSDK.zip' 
          destinationFolder: 'AgoraSDK'
          
      - task: CopyFiles@2
        inputs:
          sourceFolder: 'AgoraSDK/Agora_Native_SDK_for_Windows_v2.9.3_FULL/'
          targetFolder: ${{ parameters.workingDirectory }}
      - script: cd ${{ parameters.workingDirectory }} && ls